services:
  - type: web
    name: publicbridge
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT PublicBridge.asgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "publicbridge.onrender.com,*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: publicbridge-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: "PublicBridge.settings"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: WEB_CONCURRENCY
        value: "2"  # Reduce to save resources
      - key: DJANGO_LOG_LEVEL
        value: "INFO"  # Reduce logging to save bandwidth
    

databases:
  - name: publicbridge-db
    databaseName: publicbridge
    user: publicbridge_user
    plan: free